# Generated by Django 5.1.5 on 2025-02-09 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_request', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='creator',
            new_name='requester',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='accepted_by',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='donation_date',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='needed_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Fulfilled', 'Fulfilled')], default='Open', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_request.bloodrequest')),
            ],
        ),
    ]
